### ISSUE TITLE
[Android] WebviewBridgeManager assumes only one instance of WebView

### ISSUE THREAD

**Issue by goldenice** [alinz/react-native-webview-bridge#105]
As per my understanding of ViewManagers, ViewManagers need to be able to operate on multiple View instances. Currently, there is a boolean that says whether the bridge JS was injected or not for the whole ViewManager, which means that every WebView other than the first won't get the JS injected. The simple fix for this would be to refactor that boolean `initializedBridge` into a `Map<WebView, Boolean>`, because in that way, that boolean is save per WebView, instead of globally for the entire ViewManager.

I'll see if I can fix this easily and submit a pull request. I haven't dived into the iOS code, nor do I know if iOS shows the same behaviour, but you might want to double check that ;)

**Comment by goldenice** [comment]
This will be fixed when my PR #106 is merged :)

**Comment by ruqqq** [comment]
+1 for PR to be merged. Tested to be working fine. Great job @goldenice.

**Comment by toxicity1985** [comment]
+1 Tested and Working fine !

**Comment by CaoLiang1991** [comment]
it is wrong,see my PR  #124,the Map should be a WeakHashMap.

private Map<WebView, Boolean> initializedBridgeMap = new WeakHashMap<>();

**Comment by starlight36** [comment]
Hi~ I agree with @CaoLiang1991 's opinion. Use strong reference `HashMap` is dangers here. Because `initializedBridges`'s lifecycle belongs to the `ReactContext`. That means every WebView object can't be destroyed until the `ReactContext` released. Use `WeakHashMap` instead is a good choice to avoid this risk.

**Comment by goldenice** [comment]
Absolutely, valid point, I have to admit that I didn't think that one through! Thanks for spotting that one @CaoLiang1991 and @starlight36 ! 👍

**Comment by CaoLiang1991** [comment]
@goldenice  no thanks

**Comment by hmedney** [comment]
Hi all, this should be fixed now in Android...please see PR #150.  It uses a somewhat different approach to establish the bridge and dispatch messages from the web view to RN js.  If you spot any problems, please open a new issue...thanks!
