### ISSUE TITLE
Warning when building, Method definition for 'baseEvent' not found

### ISSUE THREAD

**Issue by KevinGrandon** [alinz/react-native-webview-bridge#11]
When building with this project, I see the following warning:

```
.../node_modules/react-native-webview-bridge/WebViewBridge/RCTWebView+WebViewBridge.m:20:17: Method definition for 'baseEvent' not found
```

**Comment by alinz** [comment]
It should be fine. I tried to expose `baseEvent` from private to public. Since objective-c is based on passing messages, at the compile time it doesn't find the implementation of `baseEvent`. However at runtime it will find it.

**Comment by KevinGrandon** [comment]
Ok, thanks!
