### ISSUE TITLE
After the release build cannot display HTML

### ISSUE THREAD

**Issue by 289420843** [alinz/react-native-webview-bridge#127]
Normal operation of the debug mode

**Comment by 289420843** [comment]
Android platform

**Comment by berkaey** [comment]
+1

**Comment by berkaey** [comment]
iOS is same.

**Comment by ivanakimov** [comment]
Does this mean the site is not showing in WebView for both platforms?

**Comment by hmedney** [comment]
@289420843 can you expand on the issue and whether it still happens with the latest from master?

**Comment by mlostekk** [comment]
Same on my side... 

if i pass 

```source={{ uri: "https://www.youtube.com/embed/70We1tmFKwU" }}```

it works.. but if i pass

```
const WEB = require('../../../assets/player/vib_and_sound/index.html');
...
source={WEB}
```

it does not show the locally saved index.html

**Comment by shenlq** [comment]
+1

**Comment by amsul** [comment]
@mlostekk that seems incorrect. The `source` shouldn't be the result of "requiring" the file. It needs to be the URI path to it.

Most likely, it would be something like this:

```js
const uriPrefix = Platform.OS === 'ios' ? '' : 'file:///android_asset/'
const uri = `${uriPrefix}index.html`

// ...
<WebViewBridge source={{ uri }} />
```
