### ISSUE TITLE
this.getWebViewHandle is not a function

### ISSUE THREAD

**Issue by liuda101** [alinz/react-native-webview-bridge#13]
I use this tool in my RN (v0.8.0) project. When I run the project, it shows this bug.

![image](https://cloud.githubusercontent.com/assets/1198861/8955138/d2c21d3c-361c-11e5-93a6-b91fbcd805a3.png)

I followed the methods on the doc.

**Comment by alinz** [comment]
@liuda101 This issue was being tracked here #12 I will let you know very soon about update. However, I welcome PR from you if you find the issue :D

**Comment by alinz** [comment]
@liuda101, I have pushed the new fix which target this issue. in react-native 0.6 and below, there was a typo in code base which forces me to use `getWebWiewHandle`. The react-native team fixed this issue and I have fixed mine as well. So please upgrade to 0.3.2 and open this issue if you see this problem again.

**Comment by liuda101** [comment]
@alinz thank you very much! Bug has gone :D
