### ISSUE TITLE
Android RN v0.30 displays blank view. Same code works on iOS.

### ISSUE THREAD

**Issue by StevenOspina** [alinz/react-native-webview-bridge#130]
I am getting a blank webview on Android; nothing displays, just a red border for some reason.

If I replace with React Native's WebView, the web page does display on Android. Working great on iOS.

**Comment by StevenOspina** [comment]
This was resolved by following the updated instructions here: https://github.com/alinz/react-native-webview-bridge/pull/118

**Comment by arnavyagnik** [comment]
Hey , got the same issue in RN 0.30 and did what the PR suggests but still on the blank screen , can you help me out please.

**Comment by StevenOspina** [comment]
@arnavyagnik I think this was the most confusing part, so make sure you are updating MainApplication.java and NOT MainActivity.java. Also, the function getPackages() already exists, so you simply add new WebViewBridgePackage().
Before:
```
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }
```
After:
```
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new WebViewBridgePackage()
      );
    }
```

**Comment by arnavyagnik** [comment]
Got it , seems that i just did not read that properly
