### ISSUE TITLE
It does not support RN 30

### ISSUE THREAD

**Issue by uc-des** [alinz/react-native-webview-bridge#132]
https://cloud.githubusercontent.com/assets/9525005/17614896/b172bc72-6087-11e6-9f7d-6cb1f68ef85c.png

**Comment by alierdogan7** [comment]
I think this is because of wrong import statements in the package.
See: http://stackoverflow.com/questions/37052798/reactnative-createclass-is-deprecated-use-react-createclass-from-react-package

The package should be updated for React Native > 0.25.0

**Comment by uc-des** [comment]
Hello alierdogan7 

I have updated these two files (index.android.js and index.ios.js) as per the RN 25, but still getting this issue

**Comment by alierdogan7** [comment]
Perhaps it's not only about import statements I think it has some other problems since it's not compatible with RN 0.30.0

https://github.com/alinz/react-native-webview-bridge/issues/109

Here the owner of the repo says that he'll release an update to keep up with new version, however there isn't any update yet.

**Comment by uc-des** [comment]
Okay Thanks

**Comment by dangnelson** [comment]
Just want to confirm the last version this works on is the April 18th release RN 0.24.0?

**Comment by hmedney** [comment]
As of PR #150, this package works with RN 0.33 and 0.34.  Let me know via a mention if you're still running into problems.

**Comment by deepmehtait** [comment]
@hmedney I am having issues in `injectedJavaScript={injectScript}` on Android. It works on iOS without any issues. Do you think your PR will fix that issue for android?
