### ISSUE TITLE
react native 0.31 cannot read property 'NavigationType' of undefined

### ISSUE THREAD

**Issue by mingkang1993** [alinz/react-native-webview-bridge#133]
react native 0.31 cannot read property 'NavigationType' of undefined

**Comment by mingkang1993** [comment]
help

**Comment by mingkang1993** [comment]
![50473d3b-f2f2-4346-a136-7f064153e522](https://cloud.githubusercontent.com/assets/9126292/17617519/39c87ed4-60ad-11e6-8581-d10ed3fe2985.png)

**Comment by PressEsc** [comment]
same for me

**Comment by alinz** [comment]
@mingkang1993 @PressEsc what is the version of this module that you guys are using?

**Comment by PressEsc** [comment]
fixed by https://github.com/alinz/react-native-webview-bridge/pull/129/files

**Comment by alinz** [comment]
closing this ticket.
