### ISSUE TITLE
import WebViewBridge error

### ISSUE THREAD

**Issue by cbcye** [alinz/react-native-webview-bridge#135]
When i use import WebViewBridge from 'react-native-webview-bridge'; to import WebViewBridge the the error like below, My RN version is 0.31

ReactNative.createClass' from the 'react-native' package. Perhaps you meant to access 'React.createClass' from the 'react' package instead?

For example, instead of:

  import React, { Component, View } from 'react-native';

You should now do:

  import React, { Component } from 'react';
  import { View } from 'react-native';

Check the release notes on how to upgrade your code - https://github.com/facebook/react-native/releases/tag/v0.25.1

**Comment by ximenxiafeng** [comment]
我也遇到了同样的情况，有解决方案吗

**Comment by cbcye** [comment]
如果是编译问题，我解决了：https://github.com/cbcye/react-native-webview-bridge ， 但是我实际上也没有跑起来，没有效果。后面删除了没用了。

**Comment by alinz** [comment]
@cbcye, @ximenxiafeng in order for me to see the tickets and issues, I need to undrestand them. would you guys please ask your questions in english. Thank you!

**Comment by cbcye** [comment]
Sorry! the latest news about this topic is , i have fix the build error and fork in my repo : https://github.com/cbcye/react-native-webview-bridge , but in the end it still can not work,  I follow the sample then use this component with WebView it can not work, not any message and error message. I don't know why.  give it up in the end.

**Comment by fanliming** [comment]
npm versin is old.

I fix this issuse with 

` npm install -save git+https://github.com/alinz/react-native-webview-bridge.git`
