### ISSUE TITLE
npm ERR! peerinvalid Peer react-native-android-tablayout@0.3.0 wants react-native@0.28

### ISSUE THREAD

**Issue by FanYeeChok** [alinz/react-native-webview-bridge#137]
Using react native version 0.30 and install:
`npm install react-native-webview-bridge`

Here is the error

> AwesomeProject admin$ npm install react-native-webview-bridge
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-webview-bridge"
> npm ERR! node v4.4.5
> npm ERR! npm  v2.15.5
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package react-native@0.30.0 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer react-native-scrollable-tab-view@0.5.3 wants react-native@>=0.20.0
> npm ERR! peerinvalid Peer react-native-tab-view@0.0.18 wants react-native@*
> npm ERR! peerinvalid Peer react-native-android-tablayout@0.3.0 wants react-native@0.28
> 
> npm ERR! Please include the following file with any support request:

**Comment by hmedney** [comment]
This is not really an issue with this package.  Please ensure a clean install of `react-native` and then retry installation of `react-native-webview-bridge`.  If an error still occurs, open a new issue.
