### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ivanakimov** [alinz/react-native-webview-bridge#141]
@alinz Would be nice to know if you're just busy, or if you're done maintaining this -- for the sake of knowing whether we should invest time building on top of this.

**Comment by jqn** [comment]
@alinz I second @ivanakimov.

**Comment by alinz** [comment]
@ivanakimov very busy at the moment, I have done some major refactor but it's not nearly ready for production. My plan was to put it into the core but things keep coming up. Please bear with me or fork it for now until I finish all my stuff.

**Comment by ivanakimov** [comment]
@alinz Fair enough. Bearing in progress ;)

**Comment by amrdraz** [comment]
Is there an estimate for the baring time ^^;

**Comment by ivanakimov** [comment]
Closing, since @hmedney is kicking ass and taking names :muscle: :smirk:

**Comment by adamkdean** [comment]
@ivanakimov could you explain what @hmedney is doing?
