### ISSUE TITLE
It does not support RN 0.32

### ISSUE THREAD

**Issue by mofan20** [alinz/react-native-webview-bridge#146]
![temp](https://cloud.githubusercontent.com/assets/2122492/18376475/251502d2-7692-11e6-90fc-6ae67f2a7ec1.png)

**Comment by xiaoboJoin** [comment]
me too ,how to fix it ?

**Comment by xiaoboJoin** [comment]
@mofan20 ,i have fixed it ,and the answer :https://github.com/alinz/react-native-webview-bridge/issues/113

**Comment by hmedney** [comment]
@mofan20 is this still an issue for you?

**Comment by alinz** [comment]
@mofan20 this is because the previous implementation of bridge uses old react-native. React, Component and other react specific features are now moved under `react` module. So @hmedney did an update and it should be working now.

**Comment by hmedney** [comment]
Closing on premise issue #113 and @alinz's response were the resolution
