### ISSUE TITLE
JS in html not work

### ISSUE THREAD

**Issue by xiaoboJoin** [alinz/react-native-webview-bridge#148]
Hi，after merge react-native-webview-bridge into my project ,and the javascript function  in html like button onclick not triggered? how to fixed it ?

**Comment by davidperrenoud** [comment]
On Android, you need to set `javaScriptEnabled={true}` in the props of the WebViewBridge component.

**Comment by hmedney** [comment]
javaScriptEnabled={true} is now the default on Android (this component doesn't make much sense without it :-))
