### ISSUE TITLE
Request: Printing webview contents

### ISSUE THREAD

**Issue by varmab** [alinz/react-native-webview-bridge#15]
Can we add support for printing webview contents to air printer?
My need is to add print button to print contents of webview.

This is code in objective-c to print webview contents just to give you an idea.
http://stackoverflow.com/questions/6544733/ios-air-print-for-uiwebview

Any ideas how?

**Comment by alinz** [comment]
@varmab, I have implemented print feature. You can now upgrade to 0.3.5 and you should be able to print.

Here's a [sample code](https://github.com/alinz/react-native-webview-bridge/blob/v0.3.5/example/Sample1/index.ios.js#L53).

Thanks for the tip and sorry about the delay.

Regards,

**Comment by Alex-Bond** [comment]
Hi! I know that this is old issue, but i have the same problem right now. I want to print WebView and your example doesn't work.
@alinz can you provide some working example?

**Comment by nhayfield** [comment]
@Alex-Bond @alinz 
I need the print functionality too. I am willing to upgrade to latest version of RN that includes your web bridge in the webview if i can then print. By the way congratulations on getting that implemented!
