### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by alinz** [alinz/react-native-webview-bridge#151]
@hmedney I beleive it's a good time to release a new version under npm. Let me know and make sure to put your name under author section in `package.json`.

**Comment by hmedney** [comment]
Hi @alinz, I added a contributors section to `package.json` and retested IOS and Android from `master` - I think it's good to go!  Do you want to tag and publish, or would you like me to do it?

**Comment by alinz** [comment]
@hmedney yeah, let's do it. Thanks for helping me out. This looks really good

**Comment by alinz** [comment]
@hmedney I has nothing to do with package.json. Anyone with write access to npm's project will be  shown there. I would like to control that one myself if you don't mind.
