### ISSUE TITLE
Android: Method not found

### ISSUE THREAD

**Issue by avishayil** [alinz/react-native-webview-bridge#153]
Sending to `WebViewBridge` works well, but the opposite way fails.
Error on chrome inspector:
![Error](http://i.imgur.com/nyRJpd6.png)

Relevant JS Code:
prop code:
````javascript
onBridgeMessage={this.onBridgeMessage.bind(this)}
````
JS code:
````javascript
    onBridgeMessage = (object) => {
        console.log(object);
    };
````

**Comment by hmedney** [comment]
Hi @avishayil, can you clarify the flow - are you sending a message from the web view to RN?  If so, can you update the issue with the web view js code?

Also, what version of Android are you using?  Thanks

**Comment by avishayil** [comment]
Hey, it was my fault, I passed old arguments I used in old fork, and that's what caused the error.
