### ISSUE TITLE
How can I open external links in safari.app from WebView?

### ISSUE THREAD

**Issue by tazmattaz** [alinz/react-native-webview-bridge#16]
Hello,

I am using this plugin, but I am facing one problem into webView. If there are external links into html content and we try to click on link it is replacing our content with new URL.
It should open in popup with close button or open in safari browser.
Have you noticed this issue?

I have inserted some patch into plugin but need to confirm from your side?

I am not a objective-s developer so please confirm if I am doing something wrong. My code is in else part.
Please review this function, 

```objective-c
- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType {
    if (webView != _webView) { return YES; }
    NSURL *url = [request URL];
    __strong WVJB_WEBVIEW_DELEGATE_TYPE* strongDelegate = _webViewDelegate;
    if ([[url scheme] isEqualToString:kCustomProtocolScheme]) {
        if ([[url host] isEqualToString:kQueueHasMessage]) {
            [self _flushMessageQueue];
        } else {
            NSLog(@"WebViewJavascriptBridge: WARNING: Received unknown WebViewJavascriptBridge command %@://%@", kCustomProtocolScheme, [url path]);
        }
        return NO;
    } else if (strongDelegate && [strongDelegate respondsToSelector:@selector(webView:shouldStartLoadWithRequest:navigationType:)]) {
        return [strongDelegate webView:webView shouldStartLoadWithRequest:request navigationType:navigationType];
    } else {
      static NSString *regexp = @"^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9-]*[a-zA-Z0-9])[.])+([A-Za-z]|[A-Za-z][A-Za-z0-9-]*[A-Za-z0-9])$";
      NSPredicate *predicate = [NSPredicate predicateWithFormat:@"SELF MATCHES %@", regexp];
      
      if ([predicate evaluateWithObject:request.URL.host]) {
        [[UIApplication sharedApplication] openURL:request.URL];
        return NO;
      } else {
        return YES;
      }
//      return YES;
    }
}
```

**Comment by alinz** [comment]
I've been busy a little bit. I will look at this today or tomorrow.

**Comment by alinz** [comment]
This is on my list to add in this weekend. I will update you!

**Comment by tazmattaz** [comment]
Ok. Thanks, I am eagerly waiting for your next release where this issue will be fixed.
Beside this, please take care of crash issue ...

THanks in advance.

**Comment by alinz** [comment]
@tazmattaz I have decided to take the path of just add only those feature that relevant to make the communication happens between native and webview. In this way the code can be maintainable and doing only one thing. I will keep this issue open so we can discuss the implementation. However, you are more than welcome to fork the project and implement all the features that you need.

**Comment by alinz** [comment]
closing this ticket. Since this is not going to be iOS releated problem and it needs to be supported on both iOS and android. Please create a new issue or give me a PR.
