### ISSUE TITLE
when using const SRC = require(...html) webview stays blank

### ISSUE THREAD

**Issue by mlostekk** [alinz/react-native-webview-bridge#162]
Anybody encountering the same issue?

When i use 

`const WEB = require('../../../assets/player/vib_and_sound/index.html');`

and 

```
<WebViewBridge
                    style={styles.webview}
                    ref="webviewbridge"
                    onBridgeMessage={this.onBridgeMessage}
                    source={WEB}  // DOES NOT WORK
                    //source={{ uri: "https://www.youtube.com/embed/70We1tmFKwU" }} // WORKS                 
                    bounces={false}
                    />
```

it does not work. When i use an http url as source, it works fine.

Anything i am forgetting to do?

**Comment by hmedney** [comment]
Hi @mlostekk, couple of things:
- Currently, React Native is unable to read arbitrary local files using `require()` - just json and image files.  As a workaround, you could place the contents of `index.html` inside a property of a local json file.
- To include html as the source for the WebViewBridge, use `source={{html: htmlString}}`.  It's the same format as [WebView](https://facebook.github.io/react-native/docs/webview.html#source)
Closing issue
