### ISSUE TITLE
sendToBridge Bug ?

### ISSUE THREAD

**Issue by ifzm** [alinz/react-native-webview-bridge#163]
![image](https://cloud.githubusercontent.com/assets/12740295/19408978/50672e7a-92fc-11e6-9057-0dc8ef7f1781.png)

I'm going to implement an example of a drop-down refresh, but invoking sendToBridge on onRefresh does not respond to JS onMessage, and I'm sure that sendToBridge is valid on the onBridgeMessage call

**Comment by hmedney** [comment]
hi @ifzm, nothing's jumping out.  Is it something I can download/clone locally to debug?

**Comment by ifzm** [comment]
So sorry. Careful examination revealed that it was my own problem )
