### ISSUE TITLE
Error in ARTShape

### ISSUE THREAD

**Issue by pawellewandowski** [alinz/react-native-webview-bridge#169]
RN: 0.36
WebView-Bridge: 0.33

![screenshot_20161109-223121](https://cloud.githubusercontent.com/assets/3199040/20155629/095cf890-a6cd-11e6-9aa9-dbe18f587c45.png)

Bug occurs often, but not always at application start

**Comment by ptilli** [comment]
Got this as well. What was the resolution for this?
