### ISSUE TITLE
Update project ReadMe to reflect this project was added to core.

### ISSUE THREAD

**Issue by jqn** [alinz/react-native-webview-bridge#173]
Please refer to this issue: https://github.com/alinz/react-native-webview-bridge/issues/109

@alinz It seems that there was an unofficial announcement about this component being added to core and it is confusing some people. Thumbs up by the way.

**Comment by alinz** [comment]
I was planning to do it, but there are some outstanding bugs from core team which causes me to stop working on it until further notice. I really want to move it into core but it needs to be fully tested and also approve by them, it is a lengthy process.

**Comment by TSMMark** [comment]
@alinz Once this component is in RN core, will the react-native-webview-bridge API remain the same? We want to implement this now, and I'm curious if we will have to make a lot of changes once it is in core.

**Comment by tioback** [comment]
I'm having a hard time migrating an app that uses the v2 branch into the RN core WebView. The API definitely isn't the same in this case.
