### ISSUE TITLE
dyld: Symbol not found: _objc_unsafeClaimAutoreleasedReturnValue

### ISSUE THREAD

**Issue by JimmyDaddy** [alinz/react-native-webview-bridge#177]
IOS: 8.1
macOS: 10.12.1
RN: 0.38.0 & 0.34.1

I got 'dyld: Symbol not found: _objc_unsafeClaimAutoreleasedReturnValue', and IOS 9+ is OK.

￼There is the error trace:
![image](https://cloud.githubusercontent.com/assets/16460813/20659317/e64ff04a-b57d-11e6-980e-bf47b460a479.png)
￼

**Comment by RtzX** [comment]
me too.this is not support iOS 8.
