### ISSUE TITLE
complie failed for RN0.41.2

### ISSUE THREAD

**Issue by MiRinZhang** [alinz/react-native-webview-bridge#209]
I used `react-native-webview-bridge@0.33.0`，but complie failed.

How do i fix this?

**Comment by 96qbhy** [comment]
I also encountered this problem.  Hope to be solved.

**Comment by MiRinZhang** [comment]
@96qbhy see this [https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/WebViewExample.js#L252](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/WebViewExample.js#L252).

It's worked for me。

In addition, If you encounter an error `react native setting imessage on a webview overrides existing values of window.postMessage....`, you can do this
<img width="666" alt="2017-02-19 14 43 13" src="https://cloud.githubusercontent.com/assets/12370585/23100074/c3215e90-f6b1-11e6-93ff-f7ef2f305e74.png">
