### ISSUE TITLE
Couldn't run sample code

### ISSUE THREAD

**Issue by varmab** [alinz/react-native-webview-bridge#21]
Any ideas about this issue?

![screen shot 2015-08-27 at 5 35 21 pm](https://cloud.githubusercontent.com/assets/4167060/9536579/4df70702-4ce2-11e5-99a8-7cc776445fb5.png)

**Comment by alinz** [comment]
Can you change the `iOS Deployment target` from 7.1 to 8.0 or above.

**Comment by hyusetiawan** [comment]
<img width="969" alt="screen shot 2015-09-04 at 1 02 52 pm" src="https://cloud.githubusercontent.com/assets/1062920/9693517/e786773a-5305-11e5-8131-e15f44c39f42.png">
I am getting almost the same error

**Comment by alinz** [comment]
@hyusetiawan @varmab can you try a new version? The thing is, you have to use react-native 0.10.0 and above. Re open if this happens again.
