### ISSUE TITLE
The installation error is above rn0.40

### ISSUE THREAD

**Issue by xuanheScript** [alinz/react-native-webview-bridge#215]
In rn0.40 and above build error, hope to adapt to the new version
![image](https://cloud.githubusercontent.com/assets/19216775/23393114/6b34e9ac-fdbb-11e6-8a17-c42ebb1cc3a7.png)

**Comment by MatthewAwesome** [comment]
I'm getting the same issue after upgrading :(

**Comment by xuanheScript** [comment]
solved

**Comment by cokealmonacid** [comment]
How do you solve this?
