### ISSUE TITLE
Crashes app while navigating webView pages from one to other

### ISSUE THREAD

**Issue by tazmattaz** [alinz/react-native-webview-bridge#22]
Hello,

I am facing crash issue with webView Bridge. When I navigate to webViewBridge page and before loading that page click on back button my app is crashing.
When I send quick messages from webView to react native its crashing too (with backspace - deleting content from webview textarea and sending content to react native on change).

Most of cases app is stuck into below line:
"" RCTLogMustFix(@"Invalid view returned from registry, expecting RKWebView, got: %@", view); ""

Full fucntion from file:

RCT_EXPORT_METHOD(callbackCleanup:(nonnull NSNumber *)reactTag)
{
  [self.bridge.uiManager addUIBlock:^(RCTUIManager *uiManager, RCTSparseArray *viewRegistry) {
    RCTWebView *view = viewRegistry[reactTag];
    if (![view isKindOfClass:[RCTWebView class]]) {
      RCTLogMustFix(@"Invalid view returned from registry, expecting RKWebView, got: %@", view);
    }

    [view callbackCleanup:reactTag];
  }];
}

Thanks in advance.

**Comment by alinz** [comment]
I might start implementing a retry method to prevent this issue. Give me couple of days. Sorry that it takes tool long to answer.

**Comment by victorkas** [comment]
Hi Alinz,

I'm also experiencing this issue "Invalid view returned from registry", is there a workaround in the mean time? 

Thanks!

**Comment by alinz** [comment]
@victorkas I have experiences this crash in simulator. However, in device, I haven't seen it yet. Have you seen this happening in device?

**Comment by victorkas** [comment]
Thanks @alinz . I traced the issue and it looks like a fetch() call in a view code that when it returns tries to send a message to WebViewBridge and causes the issue if the component has unmounted. I'm not sure if there's a cleaner way to detect if a component has unmounted, but i've added a check to avoid the crash - 
if (!this.refs.webViewBridge) return;

**Comment by tazmattaz** [comment]
Hi @alinz, yes I am facing this issue in device too. Cause of this issue I have to stop some important tasks which is using webview bridge. So I need this asap. :(

Thanks in advance.

**Comment by alinz** [comment]
@tazmattaz I need some time for this since I have to dive into React-Native code base. in a meantime can you provide a simple example that always causes this problem?

**Comment by tazmattaz** [comment]
I cannot provide the main code but this happens usually while we typing into any textarea/textfield or navigate from one page to another(both or single page use webview)  or if any age use webview and we click on back button without loading that page.
In all of above cases, my app is crashing....

**Comment by carbonphyber** [comment]
Reproducible code:
https://gist.github.com/carbonphyber/edb83eecec4a38efa1ca
I modified Sample1.
Steps to reproduce:
 1. close iOS Simulator and React Native packager if running.
 2. replace `index.ios.js` in Sample1 from [react-native-webview-bridge](https://github.com/alinz/react-native-webview-bridge) repo with the `index.ios.js` code from [this Gist](https://gist.github.com/carbonphyber/edb83eecec4a38efa1ca)
 3. `clean` (optional), `run`
 3. The two text links at the top are `Navigator` scenes. The default upon load is an empty `View`. Click the `web` text to load Netflix.com in a new scene composed of `'react-native-webview-bridge'`
 4. Click the `back` text to unload the Webview Bridge scene.
 5. Assertion failure / thrown exception described in [this issue](https://github.com/alinz/react-native-webview-bridge/issues/22) is thrown soon after the WebView Bridge appears to be animated away.

**Comment by gs-akhan** [comment]
@alinz  Hi, 
This is resolved. ?

**Comment by CorpusCallosum** [comment]
Hi I was able to circumvent the error by wrapping the cleanup call in a try-catch. I created a fork here: https://github.com/CorpusCallosum/react-native-webview-bridge

You can install it via NPM by adding this line in your package.json dependencies:
"react-native-webview-bridge": "https://github.com/CorpusCallosum/react-native-webview-bridge/tarball/master"

I'm not sure what the cleanup call is doing, but this seems to be working as expected for me now with no errors.

**Comment by alinz** [comment]
I have found and rewritten this module and I think this error has been resolved. The only thing that you have to remember is it has a hard dependency to react-native 0.16 and above. I will make support for 0.15 and 0.14 if I receive enough request. Please reopen this issue if you still encounter this problem.
