### ISSUE TITLE
RCTViewManager   RCTView 

### ISSUE THREAD

**Issue by zhangrundong** [alinz/react-native-webview-bridge#224]
![image](https://cloud.githubusercontent.com/assets/16918482/24993107/7074c874-2057-11e7-9b59-1fec7f256c0e.png)

**Comment by swaroopa94** [comment]
Same issue please anyone help

**Comment by arjshiv** [comment]
Same issue here, too

**Comment by arjshiv** [comment]
But works when pulling from `master` - so possibly related to https://github.com/alinz/react-native-webview-bridge/pull/217 ?

**Comment by vsrboth** [comment]
The issue is still here. I am using 

RN: 0.42.0
react-native-webview-bridge: 0.33.0

Can anyone help out?
Thank you so much.

**Comment by kingfun2015** [comment]
the same issue.
with using 
"react-native": "0.40.0",
"react-native-webview-bridge": "^0.33.0"

**Comment by kingfun2015** [comment]
You can see here to solve this issue.
[https://github.com/alinz/react-native-webview-bridge/issues/219](url)

**Comment by kingfun2015** [comment]
If your react-native version more than 0.40,please to change the header file like this 
#import "RCTWebViewBridge.h"

#import <UIKit/UIKit.h>

#import <React/RCTAutoInsetsProtocol.h>
#import <React/RCTConvert.h>
#import <React/RCTEventDispatcher.h>
#import <React/RCTLog.h>
#import <React/RCTUtils.h>
#import <React/RCTView.h>
#import <React/UIView+React.h>
#import <objc/runtime.h>

**Comment by iOSHw** [comment]
Nobody can give a correct answer?

**Comment by Philipwzj** [comment]
Same problem

**Comment by rogerluo410** [comment]
The functionality has already added into RN core module. 

So, the author maybe doesn't maintain the repo anymore...    

Look at: https://github.com/alinz/react-native-webview-bridge/issues/206

**Comment by eric-muyser-hs** [comment]
@kingfun2015 That doesn't work. I suspect it's building RCTView etc. into the library and conflicting. Should be dynamically linked? That's a project setting right?

**Comment by eric-muyser-hs** [comment]
I have a fix, will post diff later. Basically just move the .h includes from the .m into the .h and change to `<>` not `""`

**Comment by ericmuyser** [comment]
Fix is in PR #230 if anybody needs it
