### ISSUE TITLE
IFrame not supporting in webView Bridge

### ISSUE THREAD

**Issue by tazmattaz** [alinz/react-native-webview-bridge#24]
Hello,

I was tried to implement iFrame into webViewBridge but either it was crashing our app or showing black area. It is working fine with webView. We need asap this feature.

Thanks in Advance.

**Comment by alinz** [comment]
Sorry @tazmattaz for a long delay. I might have a solution for this, give me couple of more days to test and implement it. I will update you

**Comment by alinz** [comment]
@tazmattaz Sorry for a long delay. I have release a new version which only supports 0.16 and above. It should fixes your problem. Let me know if you still have that issue.
