### ISSUE TITLE
Please update to the latest release.

### ISSUE THREAD

**Issue by asapping99** [alinz/react-native-webview-bridge#242]
I do not have a version released after 0.33.0.
There is a bug in the IOS that has a source in the master, which can not be received in npm because of the release.
Please update to the latest release.

**Comment by abolger** [comment]
I don't think this is being actively maintained at the moment, but I have created a PR that will get you to the latest React 0.49.1: based on this source:  
https://github.com/alinz/react-native-webview-bridge/pull/243

You can al

**Comment by chansuke** [comment]
Sorry for the late action. Updated to the new release: [v0.40.1](https://github.com/alinz/react-native-webview-bridge/releases/tag/v0.40.1)
