### ISSUE TITLE
Failure on callbackHandler(@[messageArray]); when using .send()

### ISSUE THREAD

**Issue by olivierlesnicki** [alinz/react-native-webview-bridge#26]
![image](https://cloud.githubusercontent.com/assets/1705944/10323981/769e80b6-6c7e-11e5-8a4d-2ae4271c4471.png)

**Comment by alinz** [comment]
Can you post a sample code here? If I have a sample code I can fix this bug faster. Thanks

**Comment by olivierlesnicki** [comment]
This happens when no .onMessage() handlers have been defined on the react-native code size.

**Comment by alinz** [comment]
@olivierlesnicki with the new version release today you won't have the same issue any more.
