### ISSUE TITLE
How can I install the latest webview-bridge module?

### ISSUE THREAD

**Issue by ghostknow** [alinz/react-native-webview-bridge#264]
After use npm install react-native-webview-bridge --save command, I saw the source code still is using out of date coding, like var { PropTypes } = React;. How can I install the latest version? Thanks.

**Comment by chansuke** [comment]
@ghostknow Thank you for the comment.The code you read is the latest version since Alinz(the author of the library) getting busy to maintain but am planning to update the code & version in order.
