### ISSUE TITLE
PropType.func undefined and React.createClass undefined in React 16

### ISSUE THREAD

**Issue by winadiw** [alinz/react-native-webview-bridge#267]
For those of you ran into trouble using latest React and React Native, please modify the code index.android.js and index.ios.js (`/node_modules/react-native-webview-bridge/webview-bridge/index.android.js` && `/node_modules/react-native-webview-bridge/webview-bridge/index.ios.js`) as follow:

- run `npm install --save create-react-class`

- add code in the top of the file, after `var React = require('react');`
`React.createClass = require('create-react-class'); `
`var PropTypes = require('prop-types');`

- Find `var { PropTypes } = React;`, change it into `var { PropTypes } = PropTypes;`

And you are done. But please update the package if possible.

**Comment by winadiw** [comment]
@jeanniton-mnr you are welcome. Now i stopped using this package, just because built in react-native already had this feature, it is `onMessage` props.

**Comment by jeanniton-mnr** [comment]
Ok thank you for letting me know

**Comment by chansuke** [comment]
close this
