### ISSUE TITLE
[React native webView bridge] - 

### ISSUE THREAD

**Issue by tazmattaz** [alinz/react-native-webview-bridge#3]
I am using this plugin to connect webView with my React Native code. I can send multiple messages from React Native to webView. But when I try to send message from webView to React native then I can send this only once. When I tried to send message again then it is showing error message. I tried hard to fix this but unable to fix. I am using same example as defined - I just added one button into HTML page to send multiple messages to React Native.
 Please see attach screen shot.
![ios simulator screen shot 23-jun-2015 17 23 31](https://cloud.githubusercontent.com/assets/5258591/8305492/4c700e3a-19cd-11e5-9b40-2be960bb6d44.png)

**Comment by alinz** [comment]
Thanks for using my plugin,
One thing you should do is every time your onMessage callback called, you have to register your callback again. 

so here's what I have in one of my project:

```js
  registerCallback() {
    var webViewBridge = this.refs[WEBVIEW_REF];
    webViewBridge.onMessage(this.onBridgeMessage.bind(this));
  }

  onBridgeMessage(message) {
    var type = message.type;
    switch(type) {
      case 'toggle':
        //do something
        break;

      case 'ready':
        //it is ready
        break;

      case 'open-link':
        //do something here
        break

      default:
        console.log('got undefined logic for', message);
    }

    this.registerCallback();
  }

  componentDidMount() {
    this.registerCallback();
  }

  render() {
    var props = this.props;

    return (
      <WebViewBridge
        ref={WEBVIEW_REF}
        style={{ flex: 1 }}
        bounces={false}
        url={props.url}/>
    );
  }
```

So once the component mounted, I registered my callback and for every message that I receive I re-register the callback again.

**Comment by tazmattaz** [comment]
Thanks for early reply.
Yes, I tried this and it worked.

:)

**Comment by alinz** [comment]
I have a patch that fixes this issue. I will update you once it's ready.

**Comment by KevinGrandon** [comment]
> I have a patch that fixes this issue. I will update you once it's ready.

@alinz - Hey, just wondering if you had that patch handy?

I noticed that even if I register my callback immediately, I still miss messages. It's easy for me to reproduce by calling bridge.send twice. E.g., 

```
bridge.send(message1);
bridge.send(message2);
```

**Comment by alinz** [comment]
Sorry about that,
one thing you can do is wrap `send` with higher order function and call it with `setTimeout`. 

For example:

```js
function asyncCall(method) {
    return (value) => {
        setTimeout(() => { method(value); }, 0);
    };
}

bridge.send = asyncCall(bridge.send);
```

so now your `bridge.send` becomes async which might solve this problem. 

p.s. For some reason `higher order function` becomes the next big thing :P
