### ISSUE TITLE
Maximum message size?

### ISSUE THREAD

**Issue by bryanlarsen** [alinz/react-native-webview-bridge#34]
Is there a maximum message size for messages going to the webview?   Small messages are getting through, but I don't receive messages a a few kilobytes in size.

**Comment by alinz** [comment]
You should never sends a large data via message. It will slow down your app.
it needs to go through couple of layers.

```
Web Page <--> Objective-C <--> WebView <--> React-Native Code
```

use it as a signal mechanism to talk to your React-Native app. That was the whole intention.

**Comment by bryanlarsen** [comment]
I certainly hope that a couple of kilobytes isn't large.

I found the problem, it was quote marks.

**Comment by alinz** [comment]
I have an app which uses this feature and I'm passing json back and forth. To be honest with you I have even send 100 to 200 kb without any problems. However, I found that too many calls causes some issues in animation. So if you are designing your app based on that make sure you are testing the limit.

Good that you found the actual problem!

**Comment by davidperrenoud** [comment]
For the record, I was able to send 200 000 characters on Android and 2 000 000 on iOS.

**Comment by BTMouseKing** [comment]
@alinz I notice passing a large data can slow down the rendering of the webview, but i need to pass the data for rendering the chart in the webview, what is the right way to do this other than passing the data as the message?
