### ISSUE TITLE
Argument 0 (NSNumber) of RCTWebViewManager.bridgeSetup must not be null

### ISSUE THREAD

**Issue by CorpusCallosum** [alinz/react-native-webview-bridge#39]
I'm getting this error:

>Argument 0 (NSNumber) of RCTWebViewManager.bridgeSetup must not be null

What does it mean?

Thanks,
Jack

**Comment by ikeafurniture** [comment]
I'm getting a very similar error:

> Argument 0 (NSNumber) of RCTWebViewManager.onMessage must not be null

It happens when I rerender the component containing the webview as another component without a webview. Don't think I am doing anything wrong...

**Comment by alinz** [comment]
@CorpusCallosum and @ikeafurniture I don't think this issue will happen with the new release. Please try the new release. Make sure that you guys are using the react-native 0.16 and above. Please reopen this issue if you have the same error
