### ISSUE TITLE
WebViewBridge is undefined

### ISSUE THREAD

**Issue by lucars** [alinz/react-native-webview-bridge#40]
* I install react-native-webview-bridge following the installation, and run Sample1 APP successfully.
* Then I create a page using `WebViewBridgeReady` and `WebViewBridge.send` just like the Example.
* I modify the Example trying to send message manually by press a button. 
* But the document listener `WebViewBridge` is not triggered, and nothing is sent when I'm pressing the button.

I'm trying to figure out what has happened, then i found `window.WebViewBridge` is always `undefined`. Is there any step I've missed?

**Comment by gre** [comment]
Same problem to me. The example does not log any "Received message".

**Comment by gre** [comment]
This bug is because the "pathForResource" doesn't work here:

<img width="787" alt="screen shot 2015-12-07 at 14 58 57" src="https://cloud.githubusercontent.com/assets/211411/11628613/201f9568-9cf3-11e5-88ac-1e664ed2c37c.png">



Workaround:

copy webview-bridge-script.js into your own project folder in XCode...

**Comment by alinz** [comment]
@lucars the native will manage the injection. so it is guarantee to have `WebViewBridge` object in global scope. Please try the new version. I have also updated doc with more details.

@gre I have ported the bridge script into objective c code so there won't be any manual work of adding `webview-bridge-script.js` as one of bundle. 

Please reopen if you have this issue.

**Comment by gre** [comment]
great work! thanks!

**Comment by lucars** [comment]
It works. Great job. Thanks!
