### ISSUE TITLE
Can not access `WebViewBridge` global variable from webview bridge file

### ISSUE THREAD

**Issue by tazmattaz** [alinz/react-native-webview-bridge#43]
Hello,

I created webviewBridge like:

```js
var Sample2 = React.createClass({
  componentDidMount() {
    setTimeout(() => {
      this.refs.webviewbridge.sendToBridge("hahaha");
    }, 5000);
  },
  onBridgeMessage: function (message) {
    console.log(message);
  },
  render: function() {
    return (
      <WebViewBridge
        ref="webviewbridge"
        onBridgeMessage={this.onBridgeMessage}
        url="index.html"/>
    );
  }
});
```

```html
<WebViewBridge ref="myWebView" onBridgeMessage={this.onBridgeMessage} url="index.html" />
```

how can I access webViewBridge from index.html?
My index.html file as below:

```html
<html>
<head>
	<title>React App Comment stand alone page</title>
</head>
<body>
	<script type="text/javascript">
	connectWebViewJavascriptBridge: function(callback) {
		if (WebViewBridge) {
			callback(WebViewBridge);
			return;
		}
		if (window.WebViewBridge) {
			callback(window.WebViewBridge);
			return;
		}

		function handler() {
			document.removeEventListener('WebViewBridge', handler, false);
			callback(window.WebViewBridge);
		}
		document.addEventListener('WebViewBridge', handler, false);
	}
	</script>
</body>
</html>
```

Thanks in advance.

**Comment by alinz** [comment]
@tazmattaz thanks for filing an issue. I have added custom event trigger. I have updated module to support this. Also in your html code, you have a syntax error.

```js
connectWebViewJavascriptBridge: function(callback) {
------------------------------^  needs to be equal sign
```

fix that and I think you should be able to use the bridge again. Let me know if you still have that. If you manage to fix this issue please go ahead and close this ticket.

cheers

**Comment by tazmattaz** [comment]
@alinz thanks for quick reply.
I found that issue, actually the issue was with time. I put some delay before call below function  connectWebViewJavascriptBridge = function(callback) {
}

It fixed my problem. I checked and found that all previous issues has been gone(crash issues).
:+1: 

going to close this issue.

Thanks.
