### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by jjshammas** [alinz/react-native-webview-bridge#44]
I've completed Android support in my fork of this project: https://github.com/jjshammas/react-native-webview-bridge

Haven't had time to bring myself up-to-date with yours but feel free to take from mine if you have plans to work on Android.

**Comment by alinz** [comment]
@jjshammas, It looks good, would you please make a PR.

**Comment by barbarosh** [comment]
@alinz  @jjshammas Hi! When you plan include android support ?

**Comment by alinz** [comment]
@barbarosh I will spend some time in holidays to go over @jjshammas implementation and see if I can put it into the android. Also Android WebView has been added to 0.17. So I have to play around with it and see if I can extend it the way that I extend the iOS version. I will keep you posted.

**Comment by guizmaii** [comment]
+1 =)

**Comment by rmevans9** [comment]
Any update on this? I have been using @jjshammas fork to do some testing but I want to try and get to the real repo with Android support so I can keep up with @alinz updates.

**Comment by bigali** [comment]
hi , any update on android support  , I really need it

**Comment by alinz** [comment]
@jjshammas can you make a PR for this?

**Comment by priithaamer** [comment]
+1 for this :) The one from @bongole works fine for me, only the sendToBridge method seems to be missing.

**Comment by MacKentoch** [comment]
hi, thank you for this webview bridge!

Any news, plan for android support?

**Comment by CreativeManix** [comment]
please add android support.

**Comment by alinz** [comment]
I'm working on it. It requires a little bit of refinement before I can release it. Please wait a little bit longer. Thanks for waiting...

**Comment by gre** [comment]
@alinz cool :)

**Comment by stereodenis** [comment]
waiting for this feature

**Comment by alinz** [comment]
Android support is added, please give it a shot and report more bugs. It is in beta right now. I need to clean up some code. It is not as stable as iOS version. I just wanted to let everyone know. I'm closing this ticket and please open separate issues if you find anything.

**Comment by stereodenis** [comment]
@alinz thanks!
I will try it asap
