### ISSUE TITLE
sendToBridge invalid

### ISSUE THREAD

**Issue by TOP-Chao** [alinz/react-native-webview-bridge#45]
I don't understand why `sendToBridge` is used in `setTimeout`, and `onLoadingFinish`  `onLoadingStart`  `onLoadingError` is not valid.<br />
Do you have a detailed documentation?
```javascript
componentDidMount() {
    this.refs.webviewbridge.sendToBridge('message');  //invalid
    this.refs.webviewbridge.onLoadingStart(()=>{});   //invalid
    this.refs.webviewbridge.onLoadingFinish(()=>{});  //invalid
    this.refs.webviewbridge.onLoadingError(()=>{});   //invalid
    setTimeout(() => {
        //Why use delay？
        //Delay time can not be determined
        //Can there be a callback function, tell me to be able to use the correct sendToBridge
        this.refs.webviewbridge.sendToBridge('message'); //effective
    }, 1000);
}
```

**Comment by TOP-Chao** [comment]
@alinz  i realy need help.

**Comment by alinz** [comment]
@TOP-Chao, one thing you should know is that, you can't send a message from react-native to webview at the beginning. The reason for that is we don't know when the page is loading on WebView. You might have a slow connection. So what you should do is sending a message from WebView to react-native first to tell native side that you program has already been loaded and executed successfully.

So don't try to send a message from componentDidMount to WebView.

It is a good practice to start the conversation from the WebView to Native side.

**Comment by alinz** [comment]
@TOP-Chao I have changed a couple of part of it, would you try it again with new version `0.20.0` and reopen this ticket if it happens again.
