### ISSUE TITLE
Practical links when using webviews

### ISSUE THREAD

**Issue by Elyx0** [alinz/react-native-webview-bridge#46]
Maybe add http://stackoverflow.com/questions/26005641/are-cookies-in-uiwebview-accepted to the readme ? As it saved me I think others might be interested. Please close if irrelevant.

**Comment by alinz** [comment]
@Elyx0 thank you for this link, however, the purpose of this library is to simply create a bridge between react-native and webview. 

One way of solving this issue is using JWT token and pass the it to webview with this library.
