### ISSUE TITLE
How can I use WebViewBridge within ScrollView?

### ISSUE THREAD

**Issue by naeemulhaque** [alinz/react-native-webview-bridge#49]
Hi -
I am trying to show multiple url's in a scroll view. Has anyone tried this or can help point out the problem?

    <ScrollView>
        <WebViewBridge> </WebViewBridge>
        <AnotherComp/>
        <WebViewBridge> </WebViewBridge>
        <WebViewBridge> </WebViewBridge>
    </ScrollView>

**Comment by alinz** [comment]
@naeemulhaque `WebViewBridge` is the same as `WebView` with extra features. and to me `WebView` is just another `View`. You should be able to use it inside `ScrollView`. What you can do is implement your code using `WebView` and if you need an interaction the switch the component with `WebViewBridge`.

Also the provided code is technically should work. if not you have to paste more code and describe your scenario in a better context.

**Comment by naeemulhaque** [comment]
Thanks. I'll give that a try and get back.

**Comment by alinz** [comment]
@naeemulhaque I was just wondering whether you manage to solve your problem.

**Comment by ouyangdxq** [comment]
to me WebView is not just another View，is another ScrollView，and that‘s  a problem when ScrollView inside another ScrollView
