### ISSUE TITLE
Request: Add support for injecting a user script

### ISSUE THREAD

**Issue by KevinGrandon** [alinz/react-native-webview-bridge#5]
Stumbled across this project, thank you for the work here.

I think it would be really nice if there was some way to inject a user script into the webview. The idea is something like eval(), but having the content live in flat files. I think that this would make the library much easier to use.

The suggested api would be something like:
```
  componentDidMount() {
    var webviewRef = this.refs[WEBVIEW_REF];
    webviewRef.userScript('./path/to/file.js');
  }
```

**Comment by alinz** [comment]
Hello Keving,
Thanks for kind words. I have implemented the eval for the project but I have not be able to find a time to document it properly. [Here](https://github.com/alinz/react-native-webview-bridge/blob/master/jsx/webview-bridge.js#L185-L187) the code that does the execution.  At the moment you can't load the file and execute it. What  you have to do is pass the a valid javascript string into `webviewRef.eval()` method.

```js
 componentDidMount() {
    var webviewRef = this.refs[WEBVIEW_REF];
    webviewRef.eval('window.MyInternalVariable=100');
  }
```

let me know if you need more help.

**Comment by KevinGrandon** [comment]
Hi, thanks for the quick response! I agree that the eval method is useful, but I do think it would be nice to be able to wrap it in a way which could load content from a file on disk (as you might need to execute a large amount of script).

I'm going to play with this to see if I can implement what I am thinking of, and might be able to send you a pull request.

**Comment by alinz** [comment]
Agreed, you might want to look into [this](https://github.com/alinz/react-native-webview-bridge/blob/master/WebViewBridge/WebViewJavascriptBridge.m#L258-L261) since `WebViewJavascriptBridge` loads `WebViewJavascriptBridge.js.txt` as a file and injects it into webview. You might simply add a new method and duplicate the code there and replace it with some file content loader.

**Comment by KevinGrandon** [comment]
Well, maybe this is not needed. I've found a workaround, and here it is if anyone finds this in the future:

```js
var script = '(' + require('my-script.js').toString() + '());';
webviewRef.eval(script);
```

**Comment by MossP** [comment]
@KevinGrandon - Do you have an example of some script that you were able to execute inside the webview? I'm struggling just get an alert box to show.. I'm using your load & inject script and pointing to a basic test script

```
<script>
document.addEventListener("DOMContentLoaded", function(event) {
  window.alert('injected into site!');
});
</script>
```

**Comment by MossP** [comment]
OK. I worked it out. I didn't need any of the preface, just simply the call to window.alert(). That should enable me to continue. Thanks for this plugin @alinz . Great work :)

**Comment by alinz** [comment]
@MossP I have upgraded to 0.3.0. You might want to use this version instead.

**Comment by MossP** [comment]
I'll have a look at that, thank you.

**Comment by MossP** [comment]
Thanks @alinz, I'll take a look.
