### ISSUE TITLE
url and html props are depricated. Use source prop instead

### ISSUE THREAD

**Issue by stereodenis** [alinz/react-native-webview-bridge#51]
`Failed propType: Invalid prop 'source' supplied to 'WebView'`

**Comment by alinz** [comment]
I'm waiting until version react-native 0.20 stable releases. Once that one is released I will update it for you. I think you can ignore that warning. For now don't use source.

**Comment by stereodenis** [comment]
@alinz thanks!

**Comment by stereodenis** [comment]
@alinz 0.20 was released!

**Comment by alinz** [comment]
@stereodenis thanks I'm aware of that! I'm trying to find some time to sit and clean everything.

**Comment by alinz** [comment]
@stereodenis it's been upgraded to new version of react-native. closing this ticket.
