### ISSUE TITLE
Does not work in Android

### ISSUE THREAD

**Issue by bcalik** [alinz/react-native-webview-bridge#53]
```
'WebViewBridge' has no propType for native prop 'RCTWebViewBridge.source' of
native type 'Map'. If you haven't changed this prop yourself, this usually means that
your version of the native code and Javascript code are out of sync.
Updating both should make this error go away.
```

`import WebViewBridge from 'react-native-webview-bridge';`

![screenshot_20160217-173245](https://cloud.githubusercontent.com/assets/9222368/13114627/f65e2a72-d59c-11e5-8c86-ef7766047ae4.png)

**Comment by alinz** [comment]
@bcalik thanks for reporting this. Android version is in beta and needs some love, I'm trying to find some free time. However, one thing you can do and test it for me is that try not to use `source` prop and instead use `url` for now. react-native 0.20 is releases so I'm planning to upgrade both iOS and android to this version. Let me know if that works for you.

**Comment by bcalik** [comment]
@alinz: Thanks for the reply. But I already use `url` prop.
Looks like in v0.20 `url` prop automatically converted to `source`, or something like that?

I modified your `index.android.js`, and replaced every `url` with `source`, now it works.

**Comment by bcalik** [comment]
Ok another issue is, in v0.20 injectedJavascript is actually not working for Android.
https://github.com/facebook/react-native/issues/5940

So I will downgrade the version for now.

**Comment by alinz** [comment]
@bcalik I will try to work with @maraujop to get these thing iron out. be a little bit patient.

**Comment by MacKentoch** [comment]
I can't even launch android version : 
```bash
$ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-webview-bridge : Configuration with name 'default' not found.
```

My setup : 
 - "react-native": "^0.20.0",
 - "react-native-webview-bridge": "^0.19.0",
 - I run my application on my Nexus 5x so I have `android 6.0.1`.

**Comment by stereodenis** [comment]
I got white screen
"react-native": "^0.20.0"
"react-native-webview-bridge": "git+https://github.com/alinz/react-native-webview-bridge.git#859a2c4ee9c62203d51f9bc91857d24ddd806d0a"

**Comment by alinz** [comment]
@bcalik, @MacKentoch and @stereodenis I got it to work on android there was a bug in script which causes this issue. I have also added a new example which works fine on both ios and android.

Please reopen this ticket if it happens again.

**Comment by rajeshkos** [comment]
https://github.com/alinz/react-native-webview-bridge/issues/58
