### ISSUE TITLE
WebViewBridgeAndroid undefined

### ISSUE THREAD

**Issue by kemcake** [alinz/react-native-webview-bridge#57]
This line doesn't seem to work (https://github.com/alinz/react-native-webview-bridge/blob/master/android/src/main/java/com/github/alinz/reactnativewebviewbridge/WebViewBridgeManager.java#L73). So I can't send message _from_ the webview.

Any idea ? Everything else works fine, I can send message _to_ the webview

**Comment by kemcake** [comment]
Turns out that this is because I use a local file
If I take the Sample2 and instead of loading `google.com` I load a file from `file:///android_asset/view.html` I get a "WebViewBridgeAndroid is not defined"

Update: 
This `view.html` works: 
```
<!DOCTYPE html>
<html>
  <body>
      <div>Hello</div>
  </body>
</html>
```

while this one does not work:
```
<!DOCTYPE html>
<html>
  <body>
      <div>Hello</div>
  </body>
      <script type="text/javascript">
          console.log('Hello world');
      </script>
</html>
```

**Comment by alinz** [comment]
@kemcake I have used the new react-native's implementation for replacing `html` and `url` with `source`. Can you try it again and close this ticket if it works on your side.

**Comment by kemcake** [comment]
I tried with 0.20 and source props also and still experimenting the same thing :/

**Comment by alinz** [comment]
@kemcake can you try again. Unfortunatly I have a probelm with npm to publish new once. You should use direct link to this repo. Use `#v0.20.3` tag. Let me know how it goes.

**Comment by kemcake** [comment]
@alinz, Actually @Bhullnatik fixed the main problem with #66. But now it only works for the first webview mount --> #64

**Comment by tanhuisky** [comment]
i have a same problem,is there any update

**Comment by foloinfo** [comment]
@tanhuisky I added a https://github.com/alinz/react-native-webview-bridge/issues/64#issuecomment-208726935 it might help.

**Comment by tanhuisky** [comment]
@foloinfo thanks! but is does not work for me
