### ISSUE TITLE
does not build on android (gradle error)

### ISSUE THREAD

**Issue by MacKentoch** [alinz/react-native-webview-bridge#58]
I updated to `v0.20.0` but I'm afraid it does not change [#53](https://github.com/alinz/react-native-webview-bridge/issues/53#issuecomment-186863400).

**my updated setup :** 

 - "react-native": "0.20.0" 
 - "react-native-webview-bridge": "0.20.0"
 

**more info :**
1-  tested too in android studio and gradle was first still throwing this non sense (*it can be so many things*) error 
    - `Configuration with name 'default' not found.`

2- then configure a compile sdk in project structure and error changed a bit : 
```bash
Error:(20, 0) Gradle DSL method not found: 'android()'
Possible causes:
 - The project 'android' may be using a version of Gradle that does not contain the method.
 - The build file may be missing a Gradle plugin.
```

I'm sorry I can't help more since  I'm not as much at ease in Android as I am in iOS...

**Comment by alinz** [comment]
@MacKentoch thanks for detail info, can you go into examples/SampleRN20 try to run it on android by calling `npm install & react-native run-android`

**Comment by MacKentoch** [comment]
@alinz Brilliant idea!

Really nice news : 

I had a try with `examples/SampleRN20` and **it compiles and run nicely even on my device!** :+1: 


I will check the differences between the example and my project.

Thank you so much for all, you rock!

**Comment by alinz** [comment]
@MacKentoch glad that it helps. Can you double check the android setup with what I have described in [README.md](https://github.com/alinz/react-native-webview-bridge/blob/v0.20.0/README.md#android-beta) file. if I missed something would you please correct it and send me a PR.

**Comment by MacKentoch** [comment]
@alinz My issues came from `rnpm link`.

**I'm happy to finally close this *non issue*.**

If anyone has the same problem don't feel too much confident in `rnpm`.
Check 
- `setting.gradle` (*in android directory*)
- be sure of : `new File(rootProject.projectDir, '../node_modules/react-native-webview-bridge/android'`
in :
```java
include ':app', ':react-native-webview-bridge'
project(':react-native-webview-bridge').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview-bridge/android')
``` 

My problem was I had : `new File(rootProject.projectDir, '../../node_modules/react-native-webview-bridge/android'`.


>Thank you for this amazing webViewBridge. 
It offers so nice opportunities in react native applications.

**Comment by alinz** [comment]
@MacKentoch Glad you solve it and thanks for the details.
