### ISSUE TITLE
React Native Access WebView Actions

### ISSUE THREAD

**Issue by YangYouYong** [alinz/react-native-webview-bridge#59]
How can I access webview function in react native When I use your plugin?
In my webview when i tapped a button , it will calls a function named onClick , I want to response to this function in react native . so what code should i write in my script? Can you give me any suggestion? , I try to inject a JavaScript  like this 
```
var myPageScripts = function() {
  function WebViewBridgeReady(cb) {
    if (window.WebViewBridge) {
      cb(window.WebViewBridge);
      return;
    }
    function handler() {
      document.removeEventListener('WebViewBridge', handler, false);
      cb(window.WebViewBridge);
    }
    document.addEventListener('WebViewBridge', handler, false);
  }
  WebViewBridgeReady(function (WebViewBridge) {
    WebViewBirdge.onMessage = {
      onClick : function() {
        WebViewBirdge.send("onClick")
      }
    }
  });
};
myPageScripts = `(${myPageScripts.toString()}());`;
 ```

**Comment by alinz** [comment]
@YangYouYong I do have an example with latest react-native that showcases the message passing between webview and react-native. Take a look at [this one](https://github.com/alinz/react-native-webview-bridge/blob/v0.20.0/examples/SampleRN20/app.js) and if you need more help let me know.

**Comment by YangYouYong** [comment]
@alinz help me  eg:`test.html`
```
<!DOCTYPE html>
    <html>
    <head>
    <script>

    function clicked() {
        alert("clicked button");
    }
</script>
</head>

<body >
<button onclick="clicked()">Touch me</button>
</body>
</html>
```
How can i response to the function `clicked` in `test.html` ?

**Comment by YangYouYong** [comment]
@alinz I resolve it by change my test.html like this :  
```
<!DOCTYPE html>
    <html>
    <head>
    <script>

    function clicked() {
         window.WebViewBridge.send('doSomething')
    }
</script>
</head>

<body >
<button onclick="clicked()">Touch me</button>
</body>
</html>
```

**Comment by alinz** [comment]
@YangYouYong, Nice. Since you have managed to solve your problem I'm closing this ticket.
