### ISSUE TITLE
WebViewExManager.NavigationType error when starting project

### ISSUE THREAD

**Issue by KevinGrandon** [alinz/react-native-webview-bridge#6]
Hi @alinz - I'm seeing some errors when trying to use this project, and I was wondering if you had any ideas.

2015-06-30 14:19:56.194 [error][tid:com.facebook.React.JavaScript] "Error: undefined is not an object (evaluating 'WebViewExManager.NavigationType')
 stack: 
  <unknown>       index.ios.bundle:43155
  require         index.ios.bundle:244
  <unknown>       index.ios.bundle:42219
  require         index.ios.bundle:244
  <unknown>       index.ios.bundle:1110
  require         index.ios.bundle:244
  applyWithGuard  index.ios.bundle:880
  require         index.ios.bundle:195
  <unknown>       index.ios.bundle:43383
 URL: http://localhost:8081/index.ios.bundle
 line: 43155

 message: undefined is not an object (evaluating 'WebViewExManager.NavigationType')"
2015-06-30 14:19:56.245 [info][tid:com.facebook.React.JavaScript] "Running application "MyApp" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF"

**Comment by alinz** [comment]
couple of things,
- Have you added objecttiv-c folder into the project as instructed in readme file?
- if you are sending a message from webview to react-native, as soon as you get a message you have to register your callback again similar to issue #3
- would you provide react-native version and node version that you are using?
- how would I replicate this issue. Right now I'm using this library at one of my project and so far I have no issue with that.

Let me know

**Comment by KevinGrandon** [comment]
> Have you added objecttiv-c folder into the project as instructed in readme file?

Yes.


> if you are sending a message from webview to react-native, as soon as you get a message you have to register your callback again similar to issue #3

I don't think this is the issue, a I get this issue only from including react-native-webview-bridge (without sending messages yet). I am doing so by running common js modules in babel.
```
import WebViewBridge from 'react-native-webview-bridge';
```


> would you provide react-native version and node version that you are using?
node: 0.12.4
react-native: 0.6.0

**Comment by KevinGrandon** [comment]
Does anything special need to be done for this project in build phases?

**Comment by KevinGrandon** [comment]
As an update: it seems adding all of the individual files (instead of folder) seems to get me a bit further. I recommend updating the documentation, or probably packaging these files into a bundle?

**Comment by alinz** [comment]
Thanks for helping me out. I've been busy with stuff. By tomorrow I should be ready to read everything and get back to github.
Again thank you,

**Comment by Squeegy** [comment]
Getting this too. Not sure why but it apears that var `require('NativeModules')` does not return the `WebViewExManager` key. So React Native isn't finding the module for export somehow?

**Comment by Squeegy** [comment]
Yeah so I'm not enough of an XCode wizard to know what's really going on, but I did get it to work if I manually added all the `WebViewEx*.m` files to the "Compile Sources" in "Build Phases". though it's a bit weird as those files are now double referenced in my project tree.

**Comment by alinz** [comment]
I think I need to make it as a bundle project. I will get back to you. But for now, keep working with this hack solution until I get everything sorted. 

btw, thanks for reporting.

**Comment by alinz** [comment]
Ok, I push new version and I cleaned up some part of the code. It should be good for version 0.6 and above.

I have also changed the version number matched with react-native. In this way it would be a lot easier for everyone to load only specific version.

**Comment by alinz** [comment]
@Squeegy  as of 0.6, you should not use `require('NativeModules')` directly. You have to use:

```js
var React = require('react-native');
var {
  NativeModules: {
    WebViewExManager
  }
} = React
```

I have also made new version with a new technique which can mostly solve all these problem. Take a look at it and let me know if you still have that problem.
