### ISSUE TITLE
Passing `require('<SomeLocalURI>')` to .source, results in “Error while updating property ‘source’ of a view managed by RCTWebViewBridge”.

### ISSUE THREAD

**Issue by DanielKoehler** [alinz/react-native-webview-bridge#61]
The view loads correctly when passed `{uri : <URL>}`, but not when passed the result of a require() call. This latter method seems to work on the standard WebView component, is there a reason it mightn’t work with WebViewBridge?

**Comment by agenthunt** [comment]
Comparing with latest [WebView js code](https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L301) , I believe it is missing 
`source={resolveAssetSource(source)}`

**Comment by alinz** [comment]
@agenthunt good catch! I will update it now.

**Comment by agenthunt** [comment]
No problem. I created a PR related to that. If you are already fixing it , you can ignore this.

**Comment by alinz** [comment]
@agenthunt thanks for PR request, I didn't notice that. however, I can revert my changes and apply yours. I have some comment on your side, take a look!
