### ISSUE TITLE
stops working after first time

### ISSUE THREAD

**Issue by kadosh1000** [alinz/react-native-webview-bridge#64]
Hi, I am using this component and I love it, but i noticed a very wired thing.
On the first time i go on a view that uses the bridge it works perfectly, but then after exploring the app and going into another view that uses the bridge it just won't work.

I use the bridge to open links in browser, while I'm on 'Debug with Chrome' mode it works perfectly, but when I'm not in debug mode it just starts making problems.

here is the code I'm injecting to the html:

``` js
var linker = function() {
  var links = document.getElementsByTagName('a');
  for(var i=0, length=links.length; i<length; i++) {
    links[i].onclick = function(e){
      e.preventDefault();
      window.WebViewBridge.send(this.href);
    };
  }
};

window.onload = function() {
  if (window.WebViewBridge) {
    linker()
  }
  else{
    document.addEventListener('WebViewBridge', linker, false);
  }
};
```

I am using react-native-route-flux, is it possible that it have something to do with moving between routes?

Maybe it's something you should consider about the mound and unmount of the component. It seems that it won't work after the first time it gets unmounted.

**Comment by alinz** [comment]
@kadosh1000 there were couple of PR which I have merged. please try again and see if that fixes the problem.

**Comment by bigali** [comment]
i have to same problem, please help

**Comment by bigali** [comment]
is there any update on this issue

**Comment by stereodenis** [comment]
@alinz any thoughts?

**Comment by epeli** [comment]
I'm seeing this too (Android).

**Comment by malinthe** [comment]
Facing the same issue.

**Comment by foloinfo** [comment]
I'm facing same issue.
When I try to set `source` prop with user action (like `onPress` and change state with new url) it works fine, but when I try to initialize with `componentDidMount` or `constroctor`(or componentWillMount) or anything similar, it fails.
It keeps telling me `I/chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: WebViewBridge is not defined", source:  (1)` .

Any ideas?

**Comment by foloinfo** [comment]
I finally make it work consistently with `injectBridgeScript` after component is mounted.

```js
import WebViewBridge from 'react-native-webview-bridge';
class Reader extends Component {

  componentDidMount(){
    // make sure script is injected
    this.refs.webviewbridge.injectBridgeScript();
  }

  onBridgeMessage(message) {
    // call `sendToBridge` from somewhere and do whatever you want
    console.log(message);
  }

  render(){
    return(
      <WebViewBridge
        ref="webviewbridge"
        onBridgeMessage={this.onBridgeMessage.bind(this)}
        source={{uri: this.props.url}}
        injectedJavaScript={injectScript}
        javaScriptEnabled={true}
        domStorageEnabled={true}
      />
    )
  }
}

const injectScript = `
  (function () {
    if (WebViewBridge) {
      WebViewBridge.onMessage = function (message) {
        WebViewBridge.send('got message');
      };
    }
  }());
`
```

In my case I'm using `constructor` to set url state got from android native module(url got from intent), passed state as source prop to WebViewBridge. (not shown above though)
If this issue relates to #57 then try adding `injectBridgeScript()` at some point might solve problem.
This method is called in `onLoadingStart ` https://github.com/alinz/react-native-webview-bridge/blob/master/webview-bridge/index.android.js#L190 but maybe it's not sufficient.

**Comment by malinthe** [comment]
@foloinfo Tried what you mentioned but didn't experience any changes in the behavior.

**Comment by foloinfo** [comment]
@malinthe Did you try with [latest example](https://github.com/alinz/react-native-webview-bridge/blob/master/examples/SampleRN20/app.js)?
If so I don't know what's happening...

**Comment by jbail** [comment]
@foloinfo I tried your fix, but it doesn't work for me either. The WebViewBridge only works the first time. Once the WebViewBridge gets "refreshed" (go back and forward in navigation...change the source HTML...etc) it no longer sends or receives messages. I see this in the console:

I/chromium(18165): [INFO:CONSOLE(1)] "Uncaught ReferenceError: WebViewBridge is not defined"

**Comment by foloinfo** [comment]
@jbail I'm currently running WebViewBridge with this pull-request:  [fix Uncaught ReferenceError: WebViewBridgeAndroid is not defined by magicismight · Pull Request #81 · alinz/react-native-webview-bridge](https://github.com/alinz/react-native-webview-bridge/pull/81) with RN 0.22.2 and it works fine, but I'm not sure if RN version matters.
I also had a trouble with using js comments ( `//` ) in injected script. It works fine with comment if client is iOS but not Android, so don't use comment lines inside script.

That's all information I have, I really hope someone can solve this problem.

**Comment by jbail** [comment]
@foloinfo - Thank you! Pull request #81 did the trick! I no longer get the "WebViewBridge is not defined" issue and this now works as expected
