### ISSUE TITLE
source is not defined in 0.20.2

### ISSUE THREAD

**Issue by stereodenis** [alinz/react-native-webview-bridge#67]

**Comment by alinz** [comment]
@stereodenis are you using react-native 0.20?

**Comment by stereodenis** [comment]
@alinz 0.21.0

**Comment by BilalBudhani** [comment]
I'm getting the same error on react-native `0.21.0`.

**Comment by alinz** [comment]
@BilalBudhani can you double check the version you have install in `node_modules/react-native-webview-bridge`? I'm having a difficulties to publish a new version to npm.

**Comment by BilalBudhani** [comment]
@alinz Even I was facing difficulty while installing the package from npm so, I directly pointed the package to master.
```js
"react-native-webview-bridge": "github:alinz/react-native-webview-bridge",
```
and the git hash is exactly same as last commit in master `cbfd8a2472e2244126a43fcd5398b812b69c763e`

**Comment by BilalBudhani** [comment]
@alinz I think I've found the problem and resolved the issue. I'll send a PR with a fix.

**Comment by peng051410** [comment]
I got this error too!
