### ISSUE TITLE
[Android] injectScript not work!

### ISSUE THREAD

**Issue by peng051410** [alinz/react-native-webview-bridge#69]
I write bellow code:

function webViewBridgeReady(cb) {
    if (window.WebViewBridge) {
      cb(window.WebViewBridge);
      return;
    }

    function handler() {
      document.removeEventListener('WebViewBridge', handler, false);
      cb(window.WebViewBridge);
    }
    document.addEventListener('WebViewBridge', handler, false);
  }

  function goDetail(id) {
       WebViewBridge.send("jump:" + id);
  }

  webViewBridgeReady(function (webViewBridge) {
      webViewBridge.send("message from webview");
  });

the html is get from server, html have a button and click to invoke the goDetail function,but in android the
log cat say 'goDetail is not defined'.
can you help me？

**Comment by YangYouYong** [comment]
@peng051410  you should change your html code

**Comment by quentinzhang** [comment]
me either, the same code as iOS, but the injected code seems not work.

**Comment by YangYouYong** [comment]
那你能在安卓上加载出来网页吗？

**Comment by YangYouYong** [comment]
你注入的js代码没作用？ 能否QQ上讨论下呢？ 我的QQ413279774

**Comment by YangYouYong** [comment]
@quentinzhang so can you load your page in Android?

**Comment by YangYouYong** [comment]
I solve this in iOS  like #59

**Comment by YangYouYong** [comment]
@peng051410 I solve this in iOS like #59

**Comment by peng051410** [comment]
@YangYouYong  已加你qq!

**Comment by quentinzhang** [comment]
能加载出网页，只是注入的代码没有生效。已经在QQ上添加你了。

**Comment by stereodenis** [comment]
got the same issue

**Comment by g6ling** [comment]
I think what write handler() is old. change injectedScript
(function () {
                    if (WebViewBridge) {

                      WebViewBridge.onMessage = function (message) {
                        if (message === "hello from react-native") {
                          WebViewBridge.send("got the message inside webview");
                        }
                      };
                
                      WebViewBridge.send("hello from webview");
                    }
                  }());

If you read example and tried it, you will solve problem

**Comment by MacKentoch** [comment]
I experienced something interesting.

*My script works on iOS but applying it to android did not work.*

- `first` as @g6ling suggested watch [example](https://github.com/alinz/react-native-webview-bridge/blob/master/examples/SampleRN20/app.js#L17)
- `second` —*that is what is interesting*— **erase all javascript comments in your scripts!!!** 
  - it broke my script on android!!! It was why it did not work...

Illustration: 
```javascript 
const scriptNotWorking = `
 // a comment <= erase all comments like this one!!!
 alert('it won\'t work');
`;
```

```javascript 
const scriptWorking = `
 alert('it will work');
`;
```

**Comment by eremzeit** [comment]
I also am unable to inject JS on android.  If I change the type to plain old WebView with all the same props then it works.

**Comment by HADB** [comment]
I came up with the same problem.  The code works on iOS buy didn't work on Android even the simplest code as MacKentoch's.

**Comment by weremax** [comment]
Any updates or eta on a resolution to this related to android injected javascript not working, please?

**Comment by alinz** [comment]
@weremax, recently @hmedney made a contribution to the code that solves android issues. Have you tried pulling it from master branch?

**Comment by weremax** [comment]
@alinz , I have pulled from master and still am having the issue I am on react-native v 0.30.0 not the latest version could that be causing an issue.

**Comment by jenskuhrjorgensen** [comment]
GEEEEEEEZUZ christ
Thank @MacKentoch for pointing me in the direction of retarded errors. I also had problems executing injected scripts on Android whereas it worked flawless on iOS. After reading your solution I removed all comments, but it still didn't work. However, I then added **SEMICOLON's** at each and every line ending and now it works. Once again: Thanks! :D
