### ISSUE TITLE
onNavigationStateChange is not fired for WebViewBridge components

### ISSUE THREAD

**Issue by KevinGrandon** [alinz/react-native-webview-bridge#8]
onNavigationStateChange is fired for the normal react WebView components, but not WebViewBridge components.

@alinz  - any ideas why?

**Comment by alinz** [comment]
That is interesting. I have extended `RCTWebView` and added couple of new [methods](https://github.com/alinz/react-native-webview-bridge/blob/master/WebViewBridge/WebViewEx.h). I will keep this one tested one more time.

**Comment by KevinGrandon** [comment]
I'm new to this stuff, so this could be totally wrong. I tired adding some logging in various spots, and it seems we never call the original webViewDidFinishLoad method here:  https://github.com/facebook/react-native/blob/master/React/Views/RCTWebView.m#L198

It seems like this check is failing for me as well, but I'm not sure how these delegate objects are supposed to act: https://github.com/alinz/react-native-webview-bridge/blob/master/WebViewBridge/WebViewJavascriptBridge.m#L360

**Comment by alinz** [comment]
I think I know why `onNavigationStateChange` never gets fired. Because `WebViewJavascriptBridge.m` overridden react's `RCTWebView`'s `shouldStartLoadWithRequest` method. I'm working on it to make it working. I don't know how yet but I might be able to fix this.

**Comment by alinz** [comment]
I need some help. I have already posted a question on react-native https://github.com/facebook/react-native/issues/1908. I need more time to tackle this problem. 

I have also a hacky solution for it util I fix it properly(Don't get mad :dancers: ). So what you can do is injecting javascript to register a callbacks for both `onload` and `onbeforeunload ` to call `send` method to signal react-native. In this way you can simulate the behaviour of onNavigationStateChange. Ofcourse this only works for non hash URL. for route urls you can create another callback to history api. 

This is going to be crazy, I know. :(

**Comment by KevinGrandon** [comment]
No worries, good to know and thanks for following up with the React team. I wonder if it makes sense to just fork the entire component and integrate the necessary pieces if they aren't responsive.

**Comment by alinz** [comment]
@KevinGrandon I'm starting to refactoring the code. Based on that issue on react-native, I found a way to clean up code properly. I think it should be done in few days.

**Comment by KevinGrandon** [comment]
Great news - thank you so much for being responsive here. Looking forward to seeing what you come up with. :+1:

**Comment by alinz** [comment]
@KevinGrandon, I have changed a lot of things. I think it should fix the problem if you upgrade to 0.3.0. Let me know if you still have that problem.
