### ISSUE TITLE
[Android] multiple instances of WebViewBridge

### ISSUE THREAD

**Issue by alsh76** [alinz/react-native-webview-bridge#85]
When I place two different  instances of WebViewBridge (with different refs) on one page the bridge is connected twice to the first page. For IOS everything works good

**Comment by jalbrecht** [comment]
Same issue (react-native 0.27.0) on Android

**Comment by CaoLiang1991** [comment]
See my PR #124.

**Comment by hmedney** [comment]
This has been fixed; please see Issue #106
