### ISSUE TITLE
Readme for android needs to be updated

### ISSUE THREAD

**Issue by coolguy001tv** [alinz/react-native-webview-bridge#86]
In the step 

> add the following code to add the package to MainActivity.java
> mReactInstanceManager = ReactInstanceManager.builder()
>         ...
>         .addPackage(new WebViewBridgePackage())
>         ...

Actually in at lease rn 0.23.1, there's only one row needs to be inserted:

> new WebViewBridgePackage(),
> where it looks like this:
> 
> protected List<ReactPackage> getPackages() {
>         return Arrays.<ReactPackage>asList(
>             new MainReactPackage(),
>             new WebViewBridgePackage(),
>         );
>     }

**Comment by g6ling** [comment]
changed
